##### TAG DEFINITION OF ENVIRONMENT #####
# [ID, SIZE(m), X(m), Y(m), Z(m), psi(Deg)]
TAG_TRUE_RT:
  TAGS:
  # GATE Pair 1
  ## Left gate
    - [261, 0.161, 05.00, 01.69, 1.465, 000.0]
    - [262, 0.161, 05.00, 00.31, 1.465, 000.0]
  ## Right gate
    - [266, 0.161, 05.00, -0.31, 1.465, 000.0]
    - [265, 0.161, 05.00, -1.69, 1.465, 000.0]

  # GATE Pair 2
  ## Left gate
    - [268, 0.161, 5.536, 2.619, 1.465, 120.0]
    - [270, 0.161, 6.732, 3.309, 1.465, 120.0]
  ## Right gate
    - [283, 0.161, 7.269, 3.619, 1.465, 120.0]
    - [271, 0.161, 8.464, 4.309, 1.465, 120.0]

  # GATE Pair 3
  ## Left gate
    - [275, 0.161, 4.464, 2.619, 1.465, 240.0]
    - [276, 0.161, 3.269, 3.309, 1.465, 240.0]
  ## Right gate
    - [278, 0.161, 2.732, 3.619, 1.465, 240.0]
    - [279, 0.161, 1.536, 4.309, 1.465, 240.0]