##### TAG DEFINITION OF ENVIRONMENT #####
# [NAME, SIZE(m), X(m), Y(m), Z(m), psi(Deg)]
TAG_TRUE_RT:
  TAGS:
  # GATE Pair 1
    - ["SIGNBOARD01", 0.161, 05.00, 01.69, 1.465, 000.0]
    - ["SIGNBOARD02", 0.161, 05.00, 00.31, 1.465, 000.0]
  ## Right gate
    - ["SIGNBOARD03", 0.161, 05.00, -0.31, 1.465, 000.0]
    - ["SIGNBOARD04", 0.161, 05.00, -1.69, 1.465, 000.0]

  # GATE Pair 2
  ## Left gate
    - ["SIGNBOARD05", 0.161, 5.536, 2.619, 1.465, 120.0]
    - ["SIGNBOARD06", 0.161, 6.732, 3.309, 1.465, 120.0]
  ## Right gate
    - ["SIGNBOARD07", 0.161, 7.269, 3.619, 1.465, 120.0]
    - ["SIGNBOARD08", 0.161, 8.464, 4.309, 1.465, 120.0]

  # GATE Pair 3
  ## Left gate
    - ["SIGNBOARD09", 0.161, 4.464, 2.619, 1.465, 240.0]
    - ["SIGNBOARD10", 0.161, 3.269, 3.309, 1.465, 240.0]
  ## Right gate
    - ["SIGNBOARD11", 0.161, 2.732, 3.619, 1.465, 240.0]
    - ["SIGNBOARD12", 0.161, 1.536, 4.309, 1.465, 240.0]